name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the images
      run: docker-compose up -f docker/docker-compose.yml
    - name: Test service "web"
      run: curl -s --retry 10 --retry-connrefused -f http://localhost:8000/
    - name: Test service "database"
      run: curl -s --retry 10 --retry-connrefused -f http://localhost:30000/
    - name: Test service "minio"
      run: curl -s --retry 10 --retry-connrefused -f http://localhost:9000/
