name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the images
      run: docker-compose up -f docker/docker-compose.yml
    - name: Test service "web"
      run: docker run --network container:web appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8000/
    - name: Test service "database"
      run: docker run --network container:database appropriate/curl -s --retry 10 --retry-connrefused http://localhost:30000/
    - name: Test service "minio"
      run: docker run --network container:minio appropriate/curl -s --retry 10 --retry-connrefused http://localhost:9000/
